### ISSUE TITLE
Create Controller Redirection Bug

### ISSUE THREAD

**Issue by regexpressyourself** [SIU-CS/Flowchart-Creator-production#42]
@taylorflatt @reidtevonian @Mikey1848 

Hey guys,

Looks like the Controller for the Edit page isn't rendering properly. I think it's not picking up on an id when coming from the Create page. Should be able to just grab the id from the database before calling the Edit view. Can one of you guys look into this?

## Reproduction steps:
1. Go to /Flowchart/Create
2. Fill out form and submit

### Call to edit page in FlowchartController.cs
``` c#
// POST: Flowcharts/Create
// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Create(Flowchart flowchart)
{
	if (ModelState.IsValid)
	{
		flowchart.CreatedDate = DateTime.UtcNow;
		_context.Add(flowchart);
		await _context.SaveChangesAsync();
		return RedirectToAction("Edit");
	}
	return View(flowchart); // Need to pass id here I think
}
```
### Edit page controller in FlowchartController.cs
``` c#
// GET: Flowcharts/Edit/5
public async Task<IActionResult> Edit(int? id)
{
	if (id == null)
	{
		return NotFound(); // No id ever gets passed, so NotFound is called every time
	}

	var flowchart = await _context.Flowcharts.SingleOrDefaultAsync(m => m.Id == id);
	if (flowchart == null)
	{
		return NotFound();
	}

	// We have to populate the steps list via the parser.
	return View(flowchart);
}
```

**Comment by taylorflatt** [comment]
This is an easy fix. You just need to pass in the id so the method knows which stuff to pull from the db.

```c#
return RedirectToAction("Edit", new {id = flowchart.id});
```

Edit: For clarification for those who don't understand the code above, the method call requires the route as a string and route data passed in as a dictionary. So here, the Edit method requires an id so I create a new dictionary and pass in the id of the flowchart. If it required two, then there would be two items here.

Note that in the following code, you don't want to pass anything other than the model.

```c#
return View(flowchart); // Need to pass id here I think
```

This is because it is returning to the _same view_ with the model data so the user can correct errors. You don't want to redirect to the edit method if the modelstate isn't valid. Nothing was added to the database or anything.

**Comment by regexpressyourself** [comment]
@taylorflatt Ok perfect that makes sense. Missed the purpose of that block that checks the model's validity.

@reidtevonian @Mikey1848 One of you guys want to tackle this? Might be a good chance to start hopping into the codebase with an easy fix like this.

**Comment by taylorflatt** [comment]
@reidtevonian @Mikey1848 I created [a branch](https://github.com/SIU-CS/Flowchart-Creator-production/tree/fix-42) for this issue fix. I was planning on doing a bit of work tonight on stuff so if it isn't changed by the time I get on, I'll go ahead and do the changes myself so I can continue working.
